type Episode implements Node {
  id: ID!
  title: String!
  description: String
  publishDate: String
  file: String
  duration: Int
  shownotes: String
}

type EpisodeDiff {
  podcast: ID!
  added: [Episode!]
  removed: [ID!]
}

type EpisodeId {
  podcast: ID!
  episode: ID!
}

type EpisodePlayback {
  id: EpisodeId!
  position: Int
}
