type Podcast {
  id: ID!
  title: String!
  author: String
  description: String
  artwork: String
  feed: String!
  episodes(
    first: Int
    last: Int
    before: ID
    after: ID
  ): PodcastEpisodeConnection!
}

type PodcastEpisodeConnection implements Connection {
  edges: [PodcastEpisodeEdge!]!
  pageInfo: PageInfo!
}

type PodcastEpisodeEdge implements Edge {
  node: Episode!
  cursor: ID!
}
