type Podcast {
  id: ID!
  title: String!
  author: String
  description: String
  episodes: [Episode!]!
  artwork: String
  feed: String!
}

type Episode {
  id: ID!
  title: String!
  description: String
  publishDate: String
}
