type User {
  id: ID!
  subscriptions(known: [ID!]): Subscriptions!
  wpSubs: [ID!]!
  wsAuth: ID
  currentEpisode: EpisodePlayback
}

type Subscriptions {
  added: [Podcast!]!
  removed: [ID!]!
}

type SignInResult {
  user: User
  reason: FailedSigninReason
}

enum FailedSigninReason {
  unknown_ident
  duplicate_ident
  incorrect_auth
}
