type Mutation {
  signInGoogle(accessToken: ID!, wpSub: ID): User!
  signOut: Int
  subscribe(podcasts: [ID!]!): Int
  unsubscribe(podcasts: [ID!]!): Int
  parse(id: ID!): Int
  deletePodcast(id: ID!): Int
  addWPSub(sub: ID!): Int
  removeWPSub(sub: ID!): Int
  enableEpisodeNotifications(podcast: ID!): Int
  disableEpisodeNotifications(podcast: ID!): Int
}
