type Query {
  search(query: String!, limit: Int = 10): [Podcast!]!
  podcast(id: ID!): Podcast
  podcasts(ids: [ID!]!): [Podcast!]!
  episode(podId: ID!, epId: ID!): Episode
  feed(url: String!): Feed
  me: User
  metaCheck(podcasts: [CheckSum!]!): [PodcastCheckResult!]!
  episodeDiff(podcasts: [EpisodeEnc!]!): [EpisodeDiff!]!
}

input CheckSum {
  id: ID!
  meta: ID
  episodes: ID
}

input EpisodeEnc {
  id: ID!
  known: ID!
}
